
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: 'test'
        projects: 'SpacePort.Tests/*.csproj'
        arguments: '--configuration $(buildConfiguration)'

    - task: Docker@2
      inputs:
        containerRegistry: 'apiConnection'
        repository: 'spaceport-backend'
        command: 'buildAndPush'
        Dockerfile: 'SpacePort/Dockerfile'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'spaceportArtifact'
        publishLocation: 'Container'