trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  apiFolder: '$(Build.SourcesDirectory)/SpacePort'
  testFolder: '$(Build.SourcesDirectory)/SpacePort.Tests'

steps:
## kopiera in här
- task: DotNetCoreCLI@2
  displayName: Builds API and tests
  inputs:
    command: 'build'
    projects: |
      $(apiFolder)/SpacePort.csproj
      $(testFolder)/SpacePort.Tests.csproj
- task: Docker@2
  inputs:
    containerRegistry: 'sp3connection'
    repository: 'sp3api'
    command: 'buildAndPush'
    Dockerfile: SpacePort/Dockerfile

