trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
variables:
 buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'SpacePort/*.csproj'
- task: DotNetCoreCLI@2
  inputs: 
    command: test
    projects: '/SpacePort.Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- task: Docker@2
  inputs:
    containerRegistry: 'apiconnection'
    repository: 'sp3api'
    command: 'buildAndPush'
    Dockerfile: SpacePort/Dockerfile