

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  tag: '$(Build.BuildId)'

# steps:
# - task: DotNetCoreCLI@2
#   inputs:
#     command: 'build'
#     projects: 'SpacePort/*.csproj'

# - task: DotNetCoreCLI@2
#   inputs:
#     command: 'test'
#     projects: 'SpacePort.Tests/*.csproj'
#     arguments: '--configuration $(buildConfiguration)'
stages:
- stage: Build
  displayName: Build and push stage
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'apiConnection'
        repository: 'spaceport-backend'
        command: 'buildAndPush'
        Dockerfile: 'SpacePort/Dockerfile'
        tags: |
          $(tag)