trigger:
- master

pool:
 vmImage: 'ubuntu:latest'

variables:
 buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildCOnfiguration)'

- task: dotNetCoreCLI@2
  displayName: 'dotnet publish $(buildConfiguration)'
  inputs:
    command: publish
    publishWebProjects: true
    arguments: '--configuration $(buildConfiguration) --output $(build.ArtifactStagingDirectory)'
    zipAfterPublish: true

- task: PublishBuildArtifacts@1
  displayName: 'publish artifacts'

- task: Docker@2
  inputs:
    containerRegistry: 'spacepark-api-dev-connnection'
    repository: 'spacepark-api-dev-01'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'