

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'SpacePort/*.csproj'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: 'SpacePort.Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
    zipAfterPublish: false
    workingDirectory: 'SpacePort'
    

- task: Docker@2
  inputs:
    containerRegistry: 'apiConnection'
    repository: 'spaceport-backend'
    command: 'buildAndPush'
    Dockerfile: 'SpacePort/Dockerfile'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'backend'
    publishLocation: 'Container'