trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'apiConnection'
    repository: 'apirepo'
    command: 'buildAndPush'
    Dockerfile: SpacePort/Dockerfile