trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
## kopiera in här
- task: Docker@2
  inputs:
    containerRegistry: 'sp3connection'
    repository: 'sp3presentation'
    command: 'buildAndPush'
    Dockerfile: Presentation/Dockerfile