trigger:
- master

resources:
- repo: self

variables:
#  dockerRegistryServiceConnection: 'cce69a0c-b1d9-4f54-a6d0-666d6bea7ac1'
  imageRepository: 'spaceportAPIRegistry'
  #containerRegistry: 'spaceportregistry.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/SpacePort/Dockerfile'
  tag: '$(Build.BuildId)'
  apiFolder: '$(Build.SourcesDirectory)/SpacePort'
  testFolder: '$(Build.SourcesDirectory)/SpacePort.Tests'

  
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: DotNetCoreCLI@2
      displayName: Builds API and tests
      inputs:
        command: 'build'
        projects: |
          $(apiFolder)/SpacePort.csproj
          $(testFolder)/SpacePort.Tests.csproj
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(spaceportConnection)
        tags: |
          $(tag)